// playwright-export.js: pure converter from a Recaptain bundle to a
// runnable Playwright `.spec.ts` test file. Mirrors many of the collapsing and
// locator-selection rules in scripts/bundle-to-skeleton.mjs but emits TypeScript
// instead of a `wb` markdown runbook.
//
// Pure function: no chrome.*, DOM, or Node-specific APIs. Safe for the MV3
// service worker context.

const SKIP_KINDS = new Set(['focus', 'scroll', 'pause', 'resume', 'timeout', 'console']);
const IDLE_MIN_MS = 500;
const NAV_COLLAPSE_MS = 500;

export function exportPlaywrightSpec({ manifest, events, screenshotsIndex, console: _console } = {}) {
  const m = manifest || {};
  const evs = Array.isArray(events) ? events : [];
  const _shots = Array.isArray(screenshotsIndex) ? screenshotsIndex : [];

  const label = m.label || 'recorded session';
  const format = m.format || 'recaptain-recording/?';
  const startedAt = m.started_at || '';
  const durationMs = Number.isFinite(m.duration_ms) ? m.duration_ms : 0;
  const startUrl = m.start_url || '';

  const header = [
    `import { test, expect } from '@playwright/test';`,
    ``,
    `// Auto-generated by Recaptain from bundle: ${label} (${format})`,
    `// Recorded: ${startedAt}`,
    `// Duration (active): ${durationMs}ms`,
    ``,
  ];

  // Empty / no-event fallback.
  if (evs.length === 0) {
    const body = [
      `test(${jsonStr(label)}, async ({ page }) => {`,
      `  // TODO: bundle had zero events; add test steps manually.`,
    ];
    if (startUrl) body.push(`  await page.goto(${jsonStr(startUrl)});`);
    body.push(`});`, ``);
    return header.concat(body).join('\n');
  }

  // Identify the bootstrap-dedup nav (first navigation that matches start_url).
  const firstMeaningfulIdx = evs.findIndex(
    (e) => e && e.kind !== 'marker' && e.kind !== 'note' && e.kind !== 'idle',
  );
  const firstNavIdx = evs.findIndex((e) => e && e.kind === 'navigation');
  let skipFirstNav = false;
  if (startUrl && firstNavIdx !== -1 && firstNavIdx === firstMeaningfulIdx) {
    const navTo = evs[firstNavIdx].to ?? evs[firstNavIdx].url ?? null;
    if (navTo === startUrl) skipFirstNav = true;
  }

  // Result building ---------------------------------------------------------
  // We accumulate lines per step. A "step" is a test.step(...) wrapping one
  // marker's worth of events. If there are no markers, everything sits in a
  // single synthetic "session" step so we still get the convention.
  const steps = [];
  let current = newStep(label);
  steps.push(current);

  const pendingNotes = [];
  const seenStepNames = new Set();

  const pushLine = (l) => current.lines.push(l);
  const pushComment = (c) => current.lines.push(`    // ${c}`);

  // Start: page.goto(startUrl) + optional screenshot.
  if (startUrl) {
    pushLine(`    await page.goto(${jsonStr(startUrl)});`);
    pushLine(`    await page.screenshot({ path: ${jsonStr(`screenshots/${slugify(label)}-start.png`)} });`);
  }

  for (let i = 0; i < evs.length; i++) {
    const ev = evs[i];
    if (!ev || typeof ev !== 'object') continue;
    if (skipFirstNav && i === firstNavIdx) { skipFirstNav = false; continue; }

    // Collapsed-input handling: if this is a `input` (non-final) or `change`,
    // we may have already consumed it via collapseFill. Track with a skip set.
    if (ev._wbHandled) continue;

    const k = ev.kind;

    if (SKIP_KINDS.has(k)) continue;

    if (k === 'marker') {
      flushNotes(current, pendingNotes);
      // Start a fresh step.
      const raw = ev.label || 'step';
      const name = uniqueStepName(raw, seenStepNames);
      current = newStep(name);
      steps.push(current);
      // Screenshot after marker (inside the new step).
      current.lines.push(
        `    await page.screenshot({ path: ${jsonStr(`screenshots/${slugify(name)}.png`)} });`,
      );
      continue;
    }

    if (k === 'note') {
      const text = ev.text || ev.note || '';
      if (text) pendingNotes.push(text);
      continue;
    }

    if (pendingNotes.length) flushNotes(current, pendingNotes);

    if (k === 'navigation') {
      const url = ev.to ?? ev.url ?? '';
      if (!url) { pushComment(`navigation with no target url`); continue; }
      pushLine(`    await page.goto(${jsonStr(url)});`);
      pushLine(`    await page.screenshot({ path: ${jsonStr(`screenshots/${slugify(urlPathName(url) || 'nav')}.png`)} });`);
      continue;
    }

    if (k === 'tab_switch') {
      pushComment(`TODO: tab switch not auto-translated; manual adjustment needed`);
      continue;
    }

    if (k === 'submit') {
      const locStr = pickLocator(ev)?.primary;
      if (locStr) pushComment(`submit on ${locStr}`);
      else pushComment(`submit event (no locator)`);
      continue;
    }

    if (k === 'idle') {
      const d = Number(ev.duration_ms || 0);
      if (d < IDLE_MIN_MS) continue;
      // Peek ahead for the next event with a stable locator.
      const nextLoc = findNextStableLocator(evs, i + 1);
      if (nextLoc) {
        pushLine(`    await ${locatorChain(nextLoc)}.waitFor({ state: 'visible' });`);
      } else {
        pushComment(`idle ${d}ms (no stable next locator: consider a manual waitFor)`);
      }
      continue;
    }

    if (k === 'click' || k === 'dblclick') {
      const loc = pickLocator(ev);
      if (!loc?.primary) { pushComment(`${k} with no stable locator`); continue; }
      emitFallbackComments(current, loc);
      const call = k === 'dblclick' ? 'dblclick' : 'click';
      const opts = clickOptions(ev);
      // Detect click → navigation collapse.
      const nextNavIdx = findNextNavIdxWithin(evs, i, NAV_COLLAPSE_MS);
      if (k === 'click' && nextNavIdx !== -1) {
        const navUrl = evs[nextNavIdx].to ?? evs[nextNavIdx].url ?? '';
        evs[nextNavIdx]._wbHandled = true;
        pushLine(`    await Promise.all([`);
        pushLine(`      page.waitForURL(${jsonStr(navUrl)}),`);
        pushLine(`      ${locatorChain(loc.primary)}.${call}(${opts}),`);
        pushLine(`    ]);`);
      } else {
        pushLine(`    await ${locatorChain(loc.primary)}.${call}(${opts});`);
      }
      continue;
    }

    if (k === 'input' || k === 'change') {
      // Collapse consecutive input events on same locator + optional trailing change.
      const group = collectFillGroup(evs, i);
      const primaryEv = group.finalEv || group.lastInputEv;
      const loc = pickLocator(primaryEv) || pickLocator(ev);
      if (!loc?.primary) {
        pushComment(`${k} with no stable locator`);
        // Still mark the group handled so we don't loop forever.
        for (const g of group.indices) if (g !== i) evs[g]._wbHandled = true;
        continue;
      }
      emitFallbackComments(current, loc);
      // Determine masked / value.
      const isMasked = group.anyMasked;
      if (isMasked) {
        const n = group.maxLength;
        const envVar = deriveEnvVar(primaryEv);
        pushComment(`length=${n}`);
        pushLine(
          `    await ${locatorChain(loc.primary)}.fill(process.env.${envVar} ?? '');`,
        );
      } else {
        const value = group.finalValue ?? '';
        pushLine(`    await ${locatorChain(loc.primary)}.fill(${jsonStr(value)});`);
      }
      // Mark siblings handled.
      for (const g of group.indices) if (g !== i) evs[g]._wbHandled = true;
      continue;
    }

    if (k === 'key') {
      const key = normalizeKey(ev);
      if (!key) continue;
      const loc = pickLocator(ev);
      if (loc?.primary) {
        pushLine(`    await ${locatorChain(loc.primary)}.press(${jsonStr(key)});`);
      } else {
        pushLine(`    await page.keyboard.press(${jsonStr(key)});`);
      }
      continue;
    }

    if (k === 'assertion') {
      emitAssertion(current, ev);
      continue;
    }

    if (k === 'waiting_start') {
      // Find matching waiting_end (or first after this index).
      const bracket = collectWaitingBracket(evs, i);
      if (bracket) {
        const winner = chooseNetworkWinner(bracket.networkEvents);
        if (winner) {
          const path = winner.url_path || urlPath(winner.url) || winner.url;
          pushLine(
            `    await page.waitForResponse(resp => resp.url().includes(${jsonStr(path)}) && resp.ok());`,
          );
        } else {
          pushLine(`    await page.waitForLoadState('networkidle');`);
        }
        // Mark end event handled so we don't emit anything for it.
        if (bracket.endIdx !== -1) evs[bracket.endIdx]._wbHandled = true;
        // Mark network events handled (they were only relevant inside bracket).
        for (const nIdx of bracket.netIndices) evs[nIdx]._wbHandled = true;
      }
      continue;
    }

    if (k === 'waiting_end') {
      // Should have been consumed by waiting_start; emit a safety networkidle.
      pushLine(`    await page.waitForLoadState('networkidle');`);
      continue;
    }

    if (k === 'network') {
      // Standalone network events outside a bracket are noise, skip.
      continue;
    }

    pushComment(`unknown event kind: ${k}`);
  }

  flushNotes(current, pendingNotes);

  // Assemble final document.
  const out = [];
  out.push(...header);
  out.push(`test(${jsonStr(label)}, async ({ page }) => {`);
  for (let i = 0; i < steps.length; i++) {
    const s = steps[i];
    // Skip entirely empty synthetic leading step if there are real step markers.
    const allComments = s.lines.every((l) => /^\s*(\/\/|$)/.test(l));
    if (i === 0 && steps.length > 1 && s.lines.length === 0) continue;
    out.push(`  await test.step(${jsonStr(s.name)}, async () => {`);
    if (s.lines.length === 0) out.push(`    // no actions captured`);
    else out.push(...s.lines);
    out.push(`  });`);
    if (allComments && s.lines.length === 0) {/* noop */}
  }
  out.push(`});`);
  out.push('');
  return out.join('\n');
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function newStep(name) {
  return { name, lines: [] };
}

function flushNotes(step, pendingNotes) {
  if (!pendingNotes.length) return;
  for (const n of pendingNotes) step.lines.push(`    // NOTE: ${String(n).replace(/\r?\n/g, ' ')}`);
  pendingNotes.length = 0;
}

function uniqueStepName(raw, seen) {
  const name = String(raw).trim() || 'step';
  if (!seen.has(name)) { seen.add(name); return name; }
  let n = 2;
  while (seen.has(`${name} (${n})`)) n++;
  const out = `${name} (${n})`;
  seen.add(out);
  return out;
}

function jsonStr(s) { return JSON.stringify(String(s ?? '')); }

function slugify(s) {
  return String(s)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48) || 'step';
}

// Select the best locator string off an event target. Walks target.locators
// and prefers the first entry whose locator_matches entry has n === 1.
// Falls back to locators[0] if none qualify, and to target.css as a last resort.
function pickLocator(ev) {
  const locs = ev?.target?.locators;
  const matches = ev?.target?.locator_matches;
  if (Array.isArray(locs) && locs.length) {
    let primary = null;
    if (Array.isArray(matches) && matches.length) {
      for (const s of locs) {
        const m = matches.find((x) => x && x.str === s);
        if (m && m.n === 1) { primary = s; break; }
      }
    }
    if (!primary) primary = locs[0];
    const fallbacks = locs.filter((s) => s !== primary);
    return { primary, fallbacks };
  }
  const css = ev?.target?.css;
  if (css) return { primary: `locator(${JSON.stringify(css)})`, fallbacks: [] };
  return null;
}

function emitFallbackComments(step, loc) {
  for (const fb of loc.fallbacks) step.lines.push(`    // fallback: ${fb}`);
}

// Given a Playwright-style locator expression like `getByRole('button', { name: 'Go' })`
// or `locator('#x')`, return `page.<expr>`. The locator strings in the bundle
// are already valid TS expressions, so the minimal transformation is prefixing.
function locatorChain(locatorStr) {
  const s = String(locatorStr).trim();
  if (s.startsWith('page.')) return s;
  return `page.${s}`;
}

function clickOptions(ev) {
  const parts = [];
  const btn = ev.button;
  if (btn === 'right' || btn === 2) parts.push(`button: 'right'`);
  else if (btn === 'middle' || btn === 1) parts.push(`button: 'middle'`);
  const mods = Array.isArray(ev.modifiers) ? ev.modifiers.filter(Boolean) : [];
  if (mods.length) {
    parts.push(`modifiers: [${mods.map((m) => JSON.stringify(normalizeModifier(m))).join(', ')}]`);
  }
  return parts.length ? `{ ${parts.join(', ')} }` : '';
}

function normalizeModifier(m) {
  const s = String(m).toLowerCase();
  if (s === 'ctrl' || s === 'control') return 'Control';
  if (s === 'shift') return 'Shift';
  if (s === 'alt' || s === 'option') return 'Alt';
  if (s === 'meta' || s === 'cmd' || s === 'command') return 'Meta';
  return m;
}

function normalizeKey(ev) {
  const key = ev.key;
  if (!key) return null;
  const mods = Array.isArray(ev.modifiers) ? ev.modifiers.filter(Boolean) : [];
  if (mods.length === 0) return key;
  const parts = mods.map(normalizeModifier);
  parts.push(key);
  return parts.join('+');
}

function collectFillGroup(events, startIdx) {
  const first = events[startIdx];
  const primaryLoc = fingerprint(first);
  const indices = [startIdx];
  let finalValue = null;
  let finalEv = null;
  let lastInputEv = first.kind === 'input' ? first : null;
  let anyMasked = !!first.is_masked;
  let maxLength = Number.isFinite(first.value_length)
    ? first.value_length
    : (typeof first.value === 'string' ? first.value.length : 0);
  if (first.kind === 'change') { finalValue = first.value ?? null; finalEv = first; }
  else if (first.final === true) { finalValue = first.value ?? null; finalEv = first; }
  else finalValue = first.value ?? null;

  for (let j = startIdx + 1; j < events.length; j++) {
    const e = events[j];
    if (!e) continue;
    if (e.kind !== 'input' && e.kind !== 'change') break;
    if (fingerprint(e) !== primaryLoc) break;
    indices.push(j);
    if (e.is_masked) anyMasked = true;
    const len = Number.isFinite(e.value_length)
      ? e.value_length
      : (typeof e.value === 'string' ? e.value.length : 0);
    if (len > maxLength) maxLength = len;
    if (e.kind === 'change') { finalValue = e.value ?? finalValue; finalEv = e; break; }
    if (e.final === true) { finalValue = e.value ?? finalValue; finalEv = e; }
    else {
      lastInputEv = e;
      if (typeof e.value === 'string') finalValue = e.value;
    }
  }
  return { indices, finalValue, finalEv, lastInputEv, anyMasked, maxLength };
}

function fingerprint(ev) {
  const loc = pickLocator(ev);
  if (loc?.primary) return `L:${loc.primary}`;
  const t = ev?.target || {};
  return `T:${t.tag || ''}#${t.id || ''}.${t.name || ''}[${t.placeholder || ''}]`;
}

function deriveEnvVar(ev) {
  const t = ev.target;
  const raw = t.accessible_name || t.label || t.placeholder || t.name || t.id || 'FIELD';
  const cleaned = String(raw)
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 48) || 'FIELD';
  return `RECAPTAIN_SECRET_${cleaned}`;
}

function findNextStableLocator(events, fromIdx) {
  for (let i = fromIdx; i < events.length; i++) {
    const e = events[i];
    if (!e) continue;
    if (SKIP_KINDS.has(e.kind)) continue;
    if (e.kind === 'marker' || e.kind === 'note') continue;
    const loc = pickLocator(e);
    if (loc?.primary) return loc.primary;
    // Don't look past a navigation; the DOM is different.
    if (e.kind === 'navigation') return null;
  }
  return null;
}

function findNextNavIdxWithin(events, clickIdx, windowMs) {
  const click = events[clickIdx];
  const t0 = Number(click?.t);
  if (!Number.isFinite(t0)) return -1;
  for (let i = clickIdx + 1; i < events.length; i++) {
    const e = events[i];
    if (!e) continue;
    if (e.kind === 'focus' || e.kind === 'scroll' || e.kind === 'console') continue;
    if (e.kind === 'navigation') {
      const dt = Number(e.t) - t0;
      if (Number.isFinite(dt) && dt <= windowMs) return i;
      return -1;
    }
    // Anything else in between breaks the collapse.
    if (e.kind !== 'idle') return -1;
  }
  return -1;
}

function collectWaitingBracket(events, startIdx) {
  const netIndices = [];
  const networkEvents = [];
  let endIdx = -1;
  for (let j = startIdx + 1; j < events.length; j++) {
    const e = events[j];
    if (!e) continue;
    if (e.kind === 'waiting_end') { endIdx = j; break; }
    if (e.kind === 'network') { netIndices.push(j); networkEvents.push(e); }
  }
  return { endIdx, netIndices, networkEvents };
}

function chooseNetworkWinner(netEvents) {
  if (!netEvents.length) return null;
  let best = null;
  for (const n of netEvents) {
    const d = Number(n.duration_ms || 0);
    if (!best || d > Number(best.duration_ms || 0)) best = n;
  }
  // Require some minimal distinctiveness.
  if (!best || !best.url) return null;
  return best;
}

function urlPath(u) {
  try { return new URL(u).pathname; } catch { return ''; }
}

function urlPathName(u) {
  const p = urlPath(u);
  if (!p) return '';
  const parts = p.split('/').filter(Boolean);
  return parts.length ? parts[parts.length - 1] : 'root';
}

function emitAssertion(step, ev) {
  const loc = pickLocator(ev);
  const target = loc?.primary ? locatorChain(loc.primary) : null;
  const kind = ev.assertion_kind;
  const expected = ev.expected;
  if (!target) { step.lines.push(`    // assertion(${kind}) without locator`); return; }
  if (kind === 'visible') step.lines.push(`    await expect(${target}).toBeVisible();`);
  else if (kind === 'text_equals') step.lines.push(`    await expect(${target}).toHaveText(${jsonStr(expected)});`);
  else if (kind === 'text_contains') step.lines.push(`    await expect(${target}).toContainText(${jsonStr(expected)});`);
  else if (kind === 'count') step.lines.push(`    await expect(${target}).toHaveCount(${Number(expected) || 0});`);
  else if (kind === 'attr_equals') {
    const name = ev.attribute || ev.attr || 'value';
    step.lines.push(`    await expect(${target}).toHaveAttribute(${jsonStr(name)}, ${jsonStr(expected)});`);
  } else {
    step.lines.push(`    // unknown assertion_kind: ${kind}`);
  }
}
